# SPDX-License-Identifier: WTFPL
FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y && apt upgrade -y \
	; apt install -y \
		systemd \
		python3 \
	; apt clean -y

VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]
